
name: Add bugs to bugs project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Add To GitHub projects
        uses: actions/add-to-project@v0.3.0
        with:
          # URL of the project to add issues to
          project-url: https://github.com/orgs/Daily-Datapackers/projects/6
          # A GitHub personal access token with write access to the project
          github-token: ${{ secrets.BUG_TRACKER }}
          # A comma-separated list of labels to use as a filter for issue to be added
          labeled: bug, gamebreaking-bug
          # The behavior of the labels filter, AND to match all labels, OR to match any label, NOT to exclude any listed label (default is OR)
          label-operator: OR
